---
- name: Install Apache on EC2 instance
  hosts: webserver
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Apache2 (Apache HTTP Server)
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is started and enabled at boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Open firewall for Apache (if UFW is enabled)
      ufw:
        rule: allow
        name: 'Apache Full'
        state: enabled
        port: '80,443'
        proto: tcp
        comment: 'Allow Apache HTTP traffic'


